[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/infotech.html"
  status = 200

# Proxy API calls to your backend
[[redirects]]
  from = "/book"
  to = "https://ekawade.onrender.com/book"
  status = 200
  force = true

[[redirects]]
  from = "/bookings/*"
  to = "https://ekawade.onrender.com/bookings/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/export"
  to = "https://ekawade.onrender.com/export"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "https://ekawade.onrender.com/images/:splat"
  status = 200
  force = true
