[build]
  base = "Ekawade Infotech"
  publish = "Ekawade Infotech"
  command = ""

[[redirects]]
  from = "/*"
  to = "/infotech.html"
  status = 200

[[plugins]]
package = "netlify-purge-cloudflare-on-deploy"
